name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install pnpm -g
        pnpm i --no-frozen-lockfile
        pnpm build

    - name: Minio Deploy
      # You may pin to the exact commit or the version.
      # uses: hkdobrev/minio-deploy-action@98438a5d45068824d87fc8938095ae86dabc05bd
      uses: hkdobrev/minio-deploy-action@1.1.0
      with:
        # Minio endpoint of object storage host
        endpoint: secrets.S3_ENDPOINT
        # Minio access key (username)
        access_key: secrets.S3_ACCESS_KEY
        # Minio secret key (password)
        secret_key: secrets.S3_SECRET_KEY
        # Set the target minio bucket for deployment.
        bucket: metapedia
        # Set an input directory for deployment.
        source_dir: dist
        # Set a target directory for deployment (with a leading slash).
        target_dir: /
        # Trust SSL certificates with minio --insecure option
        insecure: false
